version: '3'
services:
  statushq:
    env_file: ../.env
    image: statuspal/statuspal:latest
    ports:
      - $URL_PORT:4000
    depends_on:
      - postgres
    volumes:
      - ./uploads:/statushq/uploads
    command: ["/statushq/docker/up.sh", "postgres"]
  postgres:
    image: postgres:9.5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
